name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: actions
        TAGS: v1 ${{ github.sha }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2

  # Setup S2i and Build container image
        - name: Setup and Build
          id: build_image
          uses: redhat-actions/s2i-build@v2
          with:
            path_context: '.'
            builder_image: 'registry.access.redhat.com/ubi8/php-74'
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.TAGS }}
    # Push Image to Quay registry
        - name: Push To Quay Action
          if: >
            (github.event_name == 'push' || github.event_name == 'schedule') &&
            (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
          uses: redhat-actions/push-to-registry@v2
          with:
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.TAGS}}
            registry: quay.io/${{ secrets.QUAY_USERNAME }}
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_PASSWORD }}
